# Generated by Django 5.0.7 on 2024-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sem8',
            field=models.IntegerField(default=0),
        ),
    ]
