# Generated by Django 5.0.7 on 2024-07-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_mymodel_sem1_mymodel_sem2_mymodel_sem3_mymodel_sem4_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='students',
        ),
    ]
